#version: "3.0"
#services:
#  verdaccio:
#    image: "verdaccio/verdaccio"
#    container_name: "verdaccio"
#    ports:
#      - 4873:4873
#    volumes:
#      - conf:/verdaccio/conf
#      - storage:/verdaccio/storage
#      - plugins:/verdaccio/plugins
#volumes:
#  conf:
#  storage:
#  plugins:

version: "3.0"
services:
  verdaccio:
    image: "verdaccio/verdaccio"
    container_name: "verdaccio"
    ports:
      - 4873:4873
    volumes:
      - ./conf:/verdaccio/conf
      - ./storage:/verdaccio/storage
      - ./plugins:/verdaccio/plugins

